---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.pvName }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volumes.claimSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumes.hostPath }}
