apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-chinook-populate
spec:
  template:
    spec:
      containers:
        - name: chinook-populate
          image: {{ .Values.mysql.image }}
          command: [
              "bash",
              "-c",
              "
              cat <<EOF | tee /tmp/reset.sql
              FLUSH PRIVILEGES ;
              ALTER USER 'root'@'localhost' IDENTIFIED BY 'password' ;
              EOF;

              mysqld --initialize --init-file=/tmp/reset.sql ;
              mysqld --port=3306 &

              curl -fsSL \
                  -o /tmp/db.sql \
                  'https://raw.githubusercontent.com/lerocha/chinook-database/master/ChinookDatabase/DataSources/Chinook_MySql.sql' ;

              mysql --user=root --password=password < /tmp/db.sql ;
              "
          ]
      restartPolicy: Never
