apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # Expose multiple ports
        ports:
        {{- range .Values.ports }}
        - name: {{ .name }}
          containerPort: {{ .internalTargetPort }}
          protocol: TCP
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          {{- range .Values.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            readOnly: false
          {{- end }}
      volumes:
        {{- range .Values.volumeMounts }}
        - name: {{ .name }}
          hostPath:
            path: {{ .path }}
            type: DirectoryOrCreate
        {{- end }}
