apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-hello-world
  labels:
    app: {{ .Chart.Name }}-hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-hello-world
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-hello-world
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          # Internal port the container listens on
          - containerPort: {{ .Values.service.internalTargetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
