apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}-hello-world
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalTargetPort }}
      nodePort: {{ .Values.service.externalNodePort }}
      protocol: TCP
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 6 }}

  selector:
    app: {{ .Chart.Name }}-hello-world
