apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  script-1.sh: |
    #!/usr/bin/bash
    set -m ;

    cat <<EOF | tee "/tmp/reset.sql"
    FLUSH PRIVILEGES ;
    ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' ;
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION ;

    CREATE USER '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}' ;
    GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_USER}'@'localhost' WITH GRANT OPTION ;

    EOF

    rm -rf /var/lib/mysql/* ;
    mysqld --initialize --init-file=/tmp/reset.sql ;
    echo "Database initialized" ;

    mysqld --port=${MYSQL_TCP_PORT} &
    export MYSQL_PID=$!
    echo "Started MySQL server, PID ${MYSQL_PID}"

    sleep 5;
    curl -fsSL \
        -o "/tmp/db.sql" \
        "https://raw.githubusercontent.com/lerocha/chinook-database/master/ChinookDatabase/DataSources/Chinook_MySql.sql" ;
    echo "Population script downloaded" ;

    mysql --port=${MYSQL_TCP_PORT} --user=root --password=${MYSQL_ROOT_PASSWORD} < /tmp/db.sql ;
    echo "Database populated" ;

    rm -rf /tmp/* ;
    echo "Cleanup completed" ;

    fg %1 ;
