apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-deployment-container
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.serverPort }}
              name: {{ .Chart.Name }}-p
          command: ["/usr/bin/bash"]
          args: ["/mnt/script_1.sh"]
          volumeMounts:
            - mountPath: "/mnt/"
              readOnly: true
              name: script-volume-1
          env:
            - name: MYSQL_TCP_PORT
              value: "{{ .Values.mysql.serverPort }}"
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.dbUser }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.dbPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.dbName }}
      volumes:
        - name: script-volume-1
          configMap:
            defaultMode: 0777
            name: {{ .Chart.Name }}-configmap
