apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-chinook-populate
spec:
  template:
    spec:
      containers:
        - name: chinook-populate
          image: {{ .Values.mysql.image }}
          command: [
              "bash",
              "-c",
              "
              curl -fsSL \
                  -o /tmp/db.sql \
                  'https://raw.githubusercontent.com/lerocha/chinook-database/master/ChinookDatabase/DataSources/Chinook_MySql.sql' ;

              mysql --port={{ .Values.mysql.serverPort }} --user=root --password={{ .Values.mysql.rootPassword }} < /tmp/db.sql ;
              "
          ]
      restartPolicy: Never
