apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ .Chart.Name }}-port
      protocol: {{ .Values.mysql.serverProtocol }}
      port: {{ .Values.mysql.serverPort }}
      targetPort: {{ .Values.mysql.serverPort }}
      nodePort: {{ .Values.mysql.nodePort }}
  type: LoadBalancer
  nodeSelector:
    kubernetes.io/hostname: "{{ .Values.mysql.boundHost }}"
