apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  selector:
    app: {{ .Values.mysql.app_name }}
  ports:
    - protocol: {{ .Values.mysql.serverProtocol }}
      port: {{ .Values.mysql.dbPassword }}
